services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main-slim
    network_mode: host
    volumes:
      - open-webui:/app/backend/data
    environment:
      - PORT=3000
      - OLLAMA_BASE_URL=http://vision-ws:11434/
volumes:
  open-webui: